name: CPMGen Nuget Pipeline

on:
  push:
    branches:
      - "master"
jobs:
  build-and-publish:
    permissions:
      contents: write
      id-token: write     
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0 
          
      - name: Setup dotnet
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '9.0.x'

      - name: Build
        run: dotnet build  --configuration Release

      - name: Install Versionize
        run: dotnet tool install --global Versionize
      - name: Setup git
        run: |
          git config --local user.email "mazdak.parniandg@gmail.com"
          git config --local user.name "purejoymind"
      - name: Versionize Release
        id: versionize
        run: versionize --exit-insignificant-commits
        continue-on-error: true
      - name: No release required
        if: steps.versionize.outcome != 'success'
        run: echo "Skipping Release. No release required."
      - name: Push changes to GitHub
        if: steps.versionize.outcome == 'success'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          tags: true
      - name: 'Create release'
        if: steps.versionize.outcome == 'success'
        uses: 'actions/github-script@v5'
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
          script: |
            try {
              const tags_url = context.payload.repository.tags_url + "?per_page=1"
              const result = await github.request(tags_url)
              const current_tag = result.data[0].name
              await github.rest.repos.createRelease({
                draft: false,
                generate_release_notes: true,
                name: current_tag,
                owner: context.repo.owner,
                prerelease: false,
                repo: context.repo.repo,
                tag_name: current_tag,
              });
            } catch (error) {
              core.setFailed(error.message);
            }

      - name: NuGet login (OIDC â†’ temp API key)
        if: steps.versionize.outcome == 'success'
        uses: NuGet/login@v1
        id: login
        with:
          user: 'mazdak'

      - name: NuGet push
        if: steps.versionize.outcome == 'success'
        run: dotnet nuget push **/*.nupkg --api-key ${{steps.login.outputs.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate